"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IUniswapV3SwapCallback__factory = exports.IUniswapV3MintCallback__factory = exports.IUniswapV3FlashCallback__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IUniswapV3FlashCallback__factory_1 = require("./IUniswapV3FlashCallback__factory");
Object.defineProperty(exports, "IUniswapV3FlashCallback__factory", { enumerable: true, get: function () { return IUniswapV3FlashCallback__factory_1.IUniswapV3FlashCallback__factory; } });
var IUniswapV3MintCallback__factory_1 = require("./IUniswapV3MintCallback__factory");
Object.defineProperty(exports, "IUniswapV3MintCallback__factory", { enumerable: true, get: function () { return IUniswapV3MintCallback__factory_1.IUniswapV3MintCallback__factory; } });
var IUniswapV3SwapCallback__factory_1 = require("./IUniswapV3SwapCallback__factory");
Object.defineProperty(exports, "IUniswapV3SwapCallback__factory", { enumerable: true, get: function () { return IUniswapV3SwapCallback__factory_1.IUniswapV3SwapCallback__factory; } });
