"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PairFlash__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var PairFlash__factory_1 = require("./PairFlash__factory");
Object.defineProperty(exports, "PairFlash__factory", { enumerable: true, get: function () { return PairFlash__factory_1.PairFlash__factory; } });
