"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NFTDescriptor__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var NFTDescriptor__factory_1 = require("./NFTDescriptor__factory");
Object.defineProperty(exports, "NFTDescriptor__factory", { enumerable: true, get: function () { return NFTDescriptor__factory_1.NFTDescriptor__factory; } });
