"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.IUniswapV3PoolActions__factory = exports.IUniswapV3PoolDeployer__factory = exports.IUniswapV3Pool__factory = exports.IUniswapV3Factory__factory = exports.IERC20Minimal__factory = exports.IUniswapV3SwapCallback__factory = exports.IUniswapV3MintCallback__factory = exports.IUniswapV3FlashCallback__factory = exports.V3Migrator__factory = exports.SwapRouter__factory = exports.NonfungibleTokenPositionDescriptor__factory = exports.NonfungiblePositionManager__factory = exports.NFTDescriptor__factory = exports.UniswapInterfaceMulticall__factory = exports.TickLens__factory = exports.IV3Migrator__factory = exports.ITickLens__factory = exports.ISwapRouter__factory = exports.ISelfPermit__factory = exports.IPoolInitializer__factory = exports.IPeripheryPaymentsWithFee__factory = exports.IPeripheryPayments__factory = exports.IPeripheryImmutableState__factory = exports.INonfungibleTokenPositionDescriptor__factory = exports.INonfungiblePositionManager__factory = exports.IMulticall__factory = exports.IERC721Permit__factory = exports.IERC20Metadata__factory = exports.IWETH9__factory = exports.IERC1271__factory = exports.PairFlash__factory = exports.V3SwapRouter__factory = exports.V2SwapRouter__factory = exports.SwapRouter02__factory = exports.TokenValidator__factory = exports.QuoterV2__factory = exports.Quoter__factory = exports.MixedRouteQuoterV1__factory = exports.IWETH__factory = exports.IV3SwapRouter__factory = exports.IV2SwapRouter__factory = exports.ITokenValidator__factory = exports.ISwapRouter02__factory = exports.IQuoterV2__factory = exports.IQuoter__factory = exports.IOracleSlippage__factory = exports.IMixedRouteQuoterV1__factory = exports.IImmutableState__factory = exports.IApproveAndCall__factory = exports.factories = void 0;
exports.UniswapV3Pool__factory = exports.UniswapV3Factory__factory = exports.IUniswapV3PoolState__factory = exports.IUniswapV3PoolOwnerActions__factory = exports.IUniswapV3PoolImmutables__factory = exports.IUniswapV3PoolEvents__factory = exports.IUniswapV3PoolDerivedState__factory = void 0;
exports.factories = __importStar(require("./factories"));
var IApproveAndCall__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/interfaces/IApproveAndCall__factory");
Object.defineProperty(exports, "IApproveAndCall__factory", { enumerable: true, get: function () { return IApproveAndCall__factory_1.IApproveAndCall__factory; } });
var IImmutableState__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/interfaces/IImmutableState__factory");
Object.defineProperty(exports, "IImmutableState__factory", { enumerable: true, get: function () { return IImmutableState__factory_1.IImmutableState__factory; } });
var IMixedRouteQuoterV1__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/interfaces/IMixedRouteQuoterV1__factory");
Object.defineProperty(exports, "IMixedRouteQuoterV1__factory", { enumerable: true, get: function () { return IMixedRouteQuoterV1__factory_1.IMixedRouteQuoterV1__factory; } });
var IOracleSlippage__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/interfaces/IOracleSlippage__factory");
Object.defineProperty(exports, "IOracleSlippage__factory", { enumerable: true, get: function () { return IOracleSlippage__factory_1.IOracleSlippage__factory; } });
var IQuoter__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/interfaces/IQuoter__factory");
Object.defineProperty(exports, "IQuoter__factory", { enumerable: true, get: function () { return IQuoter__factory_1.IQuoter__factory; } });
var IQuoterV2__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/interfaces/IQuoterV2__factory");
Object.defineProperty(exports, "IQuoterV2__factory", { enumerable: true, get: function () { return IQuoterV2__factory_1.IQuoterV2__factory; } });
var ISwapRouter02__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/interfaces/ISwapRouter02__factory");
Object.defineProperty(exports, "ISwapRouter02__factory", { enumerable: true, get: function () { return ISwapRouter02__factory_1.ISwapRouter02__factory; } });
var ITokenValidator__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/interfaces/ITokenValidator__factory");
Object.defineProperty(exports, "ITokenValidator__factory", { enumerable: true, get: function () { return ITokenValidator__factory_1.ITokenValidator__factory; } });
var IV2SwapRouter__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/interfaces/IV2SwapRouter__factory");
Object.defineProperty(exports, "IV2SwapRouter__factory", { enumerable: true, get: function () { return IV2SwapRouter__factory_1.IV2SwapRouter__factory; } });
var IV3SwapRouter__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/interfaces/IV3SwapRouter__factory");
Object.defineProperty(exports, "IV3SwapRouter__factory", { enumerable: true, get: function () { return IV3SwapRouter__factory_1.IV3SwapRouter__factory; } });
var IWETH__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/interfaces/IWETH__factory");
Object.defineProperty(exports, "IWETH__factory", { enumerable: true, get: function () { return IWETH__factory_1.IWETH__factory; } });
var MixedRouteQuoterV1__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/lens/MixedRouteQuoterV1__factory");
Object.defineProperty(exports, "MixedRouteQuoterV1__factory", { enumerable: true, get: function () { return MixedRouteQuoterV1__factory_1.MixedRouteQuoterV1__factory; } });
var Quoter__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/lens/Quoter__factory");
Object.defineProperty(exports, "Quoter__factory", { enumerable: true, get: function () { return Quoter__factory_1.Quoter__factory; } });
var QuoterV2__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/lens/QuoterV2__factory");
Object.defineProperty(exports, "QuoterV2__factory", { enumerable: true, get: function () { return QuoterV2__factory_1.QuoterV2__factory; } });
var TokenValidator__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/lens/TokenValidator__factory");
Object.defineProperty(exports, "TokenValidator__factory", { enumerable: true, get: function () { return TokenValidator__factory_1.TokenValidator__factory; } });
var SwapRouter02__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/SwapRouter02__factory");
Object.defineProperty(exports, "SwapRouter02__factory", { enumerable: true, get: function () { return SwapRouter02__factory_1.SwapRouter02__factory; } });
var V2SwapRouter__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/V2SwapRouter__factory");
Object.defineProperty(exports, "V2SwapRouter__factory", { enumerable: true, get: function () { return V2SwapRouter__factory_1.V2SwapRouter__factory; } });
var V3SwapRouter__factory_1 = require("./factories/swap-router-contracts/artifacts/contracts/V3SwapRouter__factory");
Object.defineProperty(exports, "V3SwapRouter__factory", { enumerable: true, get: function () { return V3SwapRouter__factory_1.V3SwapRouter__factory; } });
var PairFlash__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/examples/PairFlash__factory");
Object.defineProperty(exports, "PairFlash__factory", { enumerable: true, get: function () { return PairFlash__factory_1.PairFlash__factory; } });
var IERC1271__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/external/IERC1271__factory");
Object.defineProperty(exports, "IERC1271__factory", { enumerable: true, get: function () { return IERC1271__factory_1.IERC1271__factory; } });
var IWETH9__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/external/IWETH9__factory");
Object.defineProperty(exports, "IWETH9__factory", { enumerable: true, get: function () { return IWETH9__factory_1.IWETH9__factory; } });
var IERC20Metadata__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/IERC20Metadata__factory");
Object.defineProperty(exports, "IERC20Metadata__factory", { enumerable: true, get: function () { return IERC20Metadata__factory_1.IERC20Metadata__factory; } });
var IERC721Permit__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/IERC721Permit__factory");
Object.defineProperty(exports, "IERC721Permit__factory", { enumerable: true, get: function () { return IERC721Permit__factory_1.IERC721Permit__factory; } });
var IMulticall__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/IMulticall__factory");
Object.defineProperty(exports, "IMulticall__factory", { enumerable: true, get: function () { return IMulticall__factory_1.IMulticall__factory; } });
var INonfungiblePositionManager__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/INonfungiblePositionManager__factory");
Object.defineProperty(exports, "INonfungiblePositionManager__factory", { enumerable: true, get: function () { return INonfungiblePositionManager__factory_1.INonfungiblePositionManager__factory; } });
var INonfungibleTokenPositionDescriptor__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/INonfungibleTokenPositionDescriptor__factory");
Object.defineProperty(exports, "INonfungibleTokenPositionDescriptor__factory", { enumerable: true, get: function () { return INonfungibleTokenPositionDescriptor__factory_1.INonfungibleTokenPositionDescriptor__factory; } });
var IPeripheryImmutableState__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/IPeripheryImmutableState__factory");
Object.defineProperty(exports, "IPeripheryImmutableState__factory", { enumerable: true, get: function () { return IPeripheryImmutableState__factory_1.IPeripheryImmutableState__factory; } });
var IPeripheryPayments__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/IPeripheryPayments__factory");
Object.defineProperty(exports, "IPeripheryPayments__factory", { enumerable: true, get: function () { return IPeripheryPayments__factory_1.IPeripheryPayments__factory; } });
var IPeripheryPaymentsWithFee__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/IPeripheryPaymentsWithFee__factory");
Object.defineProperty(exports, "IPeripheryPaymentsWithFee__factory", { enumerable: true, get: function () { return IPeripheryPaymentsWithFee__factory_1.IPeripheryPaymentsWithFee__factory; } });
var IPoolInitializer__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/IPoolInitializer__factory");
Object.defineProperty(exports, "IPoolInitializer__factory", { enumerable: true, get: function () { return IPoolInitializer__factory_1.IPoolInitializer__factory; } });
var ISelfPermit__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/ISelfPermit__factory");
Object.defineProperty(exports, "ISelfPermit__factory", { enumerable: true, get: function () { return ISelfPermit__factory_1.ISelfPermit__factory; } });
var ISwapRouter__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/ISwapRouter__factory");
Object.defineProperty(exports, "ISwapRouter__factory", { enumerable: true, get: function () { return ISwapRouter__factory_1.ISwapRouter__factory; } });
var ITickLens__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/ITickLens__factory");
Object.defineProperty(exports, "ITickLens__factory", { enumerable: true, get: function () { return ITickLens__factory_1.ITickLens__factory; } });
var IV3Migrator__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/interfaces/IV3Migrator__factory");
Object.defineProperty(exports, "IV3Migrator__factory", { enumerable: true, get: function () { return IV3Migrator__factory_1.IV3Migrator__factory; } });
var TickLens__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/lens/TickLens__factory");
Object.defineProperty(exports, "TickLens__factory", { enumerable: true, get: function () { return TickLens__factory_1.TickLens__factory; } });
var UniswapInterfaceMulticall__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/lens/UniswapInterfaceMulticall__factory");
Object.defineProperty(exports, "UniswapInterfaceMulticall__factory", { enumerable: true, get: function () { return UniswapInterfaceMulticall__factory_1.UniswapInterfaceMulticall__factory; } });
var NFTDescriptor__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/libraries/NFTDescriptor__factory");
Object.defineProperty(exports, "NFTDescriptor__factory", { enumerable: true, get: function () { return NFTDescriptor__factory_1.NFTDescriptor__factory; } });
var NonfungiblePositionManager__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/NonfungiblePositionManager__factory");
Object.defineProperty(exports, "NonfungiblePositionManager__factory", { enumerable: true, get: function () { return NonfungiblePositionManager__factory_1.NonfungiblePositionManager__factory; } });
var NonfungibleTokenPositionDescriptor__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/NonfungibleTokenPositionDescriptor__factory");
Object.defineProperty(exports, "NonfungibleTokenPositionDescriptor__factory", { enumerable: true, get: function () { return NonfungibleTokenPositionDescriptor__factory_1.NonfungibleTokenPositionDescriptor__factory; } });
var SwapRouter__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/SwapRouter__factory");
Object.defineProperty(exports, "SwapRouter__factory", { enumerable: true, get: function () { return SwapRouter__factory_1.SwapRouter__factory; } });
var V3Migrator__factory_1 = require("./factories/swap-router-contracts/node_modules/@uniswap/v3-periphery/artifacts/contracts/V3Migrator__factory");
Object.defineProperty(exports, "V3Migrator__factory", { enumerable: true, get: function () { return V3Migrator__factory_1.V3Migrator__factory; } });
var IUniswapV3FlashCallback__factory_1 = require("./factories/v3-core/artifacts/contracts/interfaces/callback/IUniswapV3FlashCallback__factory");
Object.defineProperty(exports, "IUniswapV3FlashCallback__factory", { enumerable: true, get: function () { return IUniswapV3FlashCallback__factory_1.IUniswapV3FlashCallback__factory; } });
var IUniswapV3MintCallback__factory_1 = require("./factories/v3-core/artifacts/contracts/interfaces/callback/IUniswapV3MintCallback__factory");
Object.defineProperty(exports, "IUniswapV3MintCallback__factory", { enumerable: true, get: function () { return IUniswapV3MintCallback__factory_1.IUniswapV3MintCallback__factory; } });
var IUniswapV3SwapCallback__factory_1 = require("./factories/v3-core/artifacts/contracts/interfaces/callback/IUniswapV3SwapCallback__factory");
Object.defineProperty(exports, "IUniswapV3SwapCallback__factory", { enumerable: true, get: function () { return IUniswapV3SwapCallback__factory_1.IUniswapV3SwapCallback__factory; } });
var IERC20Minimal__factory_1 = require("./factories/v3-core/artifacts/contracts/interfaces/IERC20Minimal__factory");
Object.defineProperty(exports, "IERC20Minimal__factory", { enumerable: true, get: function () { return IERC20Minimal__factory_1.IERC20Minimal__factory; } });
var IUniswapV3Factory__factory_1 = require("./factories/v3-core/artifacts/contracts/interfaces/IUniswapV3Factory__factory");
Object.defineProperty(exports, "IUniswapV3Factory__factory", { enumerable: true, get: function () { return IUniswapV3Factory__factory_1.IUniswapV3Factory__factory; } });
var IUniswapV3Pool__factory_1 = require("./factories/v3-core/artifacts/contracts/interfaces/IUniswapV3Pool__factory");
Object.defineProperty(exports, "IUniswapV3Pool__factory", { enumerable: true, get: function () { return IUniswapV3Pool__factory_1.IUniswapV3Pool__factory; } });
var IUniswapV3PoolDeployer__factory_1 = require("./factories/v3-core/artifacts/contracts/interfaces/IUniswapV3PoolDeployer__factory");
Object.defineProperty(exports, "IUniswapV3PoolDeployer__factory", { enumerable: true, get: function () { return IUniswapV3PoolDeployer__factory_1.IUniswapV3PoolDeployer__factory; } });
var IUniswapV3PoolActions__factory_1 = require("./factories/v3-core/artifacts/contracts/interfaces/pool/IUniswapV3PoolActions__factory");
Object.defineProperty(exports, "IUniswapV3PoolActions__factory", { enumerable: true, get: function () { return IUniswapV3PoolActions__factory_1.IUniswapV3PoolActions__factory; } });
var IUniswapV3PoolDerivedState__factory_1 = require("./factories/v3-core/artifacts/contracts/interfaces/pool/IUniswapV3PoolDerivedState__factory");
Object.defineProperty(exports, "IUniswapV3PoolDerivedState__factory", { enumerable: true, get: function () { return IUniswapV3PoolDerivedState__factory_1.IUniswapV3PoolDerivedState__factory; } });
var IUniswapV3PoolEvents__factory_1 = require("./factories/v3-core/artifacts/contracts/interfaces/pool/IUniswapV3PoolEvents__factory");
Object.defineProperty(exports, "IUniswapV3PoolEvents__factory", { enumerable: true, get: function () { return IUniswapV3PoolEvents__factory_1.IUniswapV3PoolEvents__factory; } });
var IUniswapV3PoolImmutables__factory_1 = require("./factories/v3-core/artifacts/contracts/interfaces/pool/IUniswapV3PoolImmutables__factory");
Object.defineProperty(exports, "IUniswapV3PoolImmutables__factory", { enumerable: true, get: function () { return IUniswapV3PoolImmutables__factory_1.IUniswapV3PoolImmutables__factory; } });
var IUniswapV3PoolOwnerActions__factory_1 = require("./factories/v3-core/artifacts/contracts/interfaces/pool/IUniswapV3PoolOwnerActions__factory");
Object.defineProperty(exports, "IUniswapV3PoolOwnerActions__factory", { enumerable: true, get: function () { return IUniswapV3PoolOwnerActions__factory_1.IUniswapV3PoolOwnerActions__factory; } });
var IUniswapV3PoolState__factory_1 = require("./factories/v3-core/artifacts/contracts/interfaces/pool/IUniswapV3PoolState__factory");
Object.defineProperty(exports, "IUniswapV3PoolState__factory", { enumerable: true, get: function () { return IUniswapV3PoolState__factory_1.IUniswapV3PoolState__factory; } });
var UniswapV3Factory__factory_1 = require("./factories/v3-core/artifacts/contracts/UniswapV3Factory__factory");
Object.defineProperty(exports, "UniswapV3Factory__factory", { enumerable: true, get: function () { return UniswapV3Factory__factory_1.UniswapV3Factory__factory; } });
var UniswapV3Pool__factory_1 = require("./factories/v3-core/artifacts/contracts/UniswapV3Pool__factory");
Object.defineProperty(exports, "UniswapV3Pool__factory", { enumerable: true, get: function () { return UniswapV3Pool__factory_1.UniswapV3Pool__factory; } });
