"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.IV3Migrator__factory = exports.ITickLens__factory = exports.ISwapRouter__factory = exports.ISelfPermit__factory = exports.IQuoterV2__factory = exports.IQuoter__factory = exports.IPoolInitializer__factory = exports.IPeripheryPaymentsWithFee__factory = exports.IPeripheryPayments__factory = exports.IPeripheryImmutableState__factory = exports.INonfungibleTokenPositionDescriptor__factory = exports.INonfungiblePositionManager__factory = exports.IMulticall__factory = exports.IERC721Permit__factory = exports.IERC20Metadata__factory = exports.external = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.external = __importStar(require("./external"));
var IERC20Metadata__factory_1 = require("./IERC20Metadata__factory");
Object.defineProperty(exports, "IERC20Metadata__factory", { enumerable: true, get: function () { return IERC20Metadata__factory_1.IERC20Metadata__factory; } });
var IERC721Permit__factory_1 = require("./IERC721Permit__factory");
Object.defineProperty(exports, "IERC721Permit__factory", { enumerable: true, get: function () { return IERC721Permit__factory_1.IERC721Permit__factory; } });
var IMulticall__factory_1 = require("./IMulticall__factory");
Object.defineProperty(exports, "IMulticall__factory", { enumerable: true, get: function () { return IMulticall__factory_1.IMulticall__factory; } });
var INonfungiblePositionManager__factory_1 = require("./INonfungiblePositionManager__factory");
Object.defineProperty(exports, "INonfungiblePositionManager__factory", { enumerable: true, get: function () { return INonfungiblePositionManager__factory_1.INonfungiblePositionManager__factory; } });
var INonfungibleTokenPositionDescriptor__factory_1 = require("./INonfungibleTokenPositionDescriptor__factory");
Object.defineProperty(exports, "INonfungibleTokenPositionDescriptor__factory", { enumerable: true, get: function () { return INonfungibleTokenPositionDescriptor__factory_1.INonfungibleTokenPositionDescriptor__factory; } });
var IPeripheryImmutableState__factory_1 = require("./IPeripheryImmutableState__factory");
Object.defineProperty(exports, "IPeripheryImmutableState__factory", { enumerable: true, get: function () { return IPeripheryImmutableState__factory_1.IPeripheryImmutableState__factory; } });
var IPeripheryPayments__factory_1 = require("./IPeripheryPayments__factory");
Object.defineProperty(exports, "IPeripheryPayments__factory", { enumerable: true, get: function () { return IPeripheryPayments__factory_1.IPeripheryPayments__factory; } });
var IPeripheryPaymentsWithFee__factory_1 = require("./IPeripheryPaymentsWithFee__factory");
Object.defineProperty(exports, "IPeripheryPaymentsWithFee__factory", { enumerable: true, get: function () { return IPeripheryPaymentsWithFee__factory_1.IPeripheryPaymentsWithFee__factory; } });
var IPoolInitializer__factory_1 = require("./IPoolInitializer__factory");
Object.defineProperty(exports, "IPoolInitializer__factory", { enumerable: true, get: function () { return IPoolInitializer__factory_1.IPoolInitializer__factory; } });
var IQuoter__factory_1 = require("./IQuoter__factory");
Object.defineProperty(exports, "IQuoter__factory", { enumerable: true, get: function () { return IQuoter__factory_1.IQuoter__factory; } });
var IQuoterV2__factory_1 = require("./IQuoterV2__factory");
Object.defineProperty(exports, "IQuoterV2__factory", { enumerable: true, get: function () { return IQuoterV2__factory_1.IQuoterV2__factory; } });
var ISelfPermit__factory_1 = require("./ISelfPermit__factory");
Object.defineProperty(exports, "ISelfPermit__factory", { enumerable: true, get: function () { return ISelfPermit__factory_1.ISelfPermit__factory; } });
var ISwapRouter__factory_1 = require("./ISwapRouter__factory");
Object.defineProperty(exports, "ISwapRouter__factory", { enumerable: true, get: function () { return ISwapRouter__factory_1.ISwapRouter__factory; } });
var ITickLens__factory_1 = require("./ITickLens__factory");
Object.defineProperty(exports, "ITickLens__factory", { enumerable: true, get: function () { return ITickLens__factory_1.ITickLens__factory; } });
var IV3Migrator__factory_1 = require("./IV3Migrator__factory");
Object.defineProperty(exports, "IV3Migrator__factory", { enumerable: true, get: function () { return IV3Migrator__factory_1.IV3Migrator__factory; } });
